name: Show Me the S3cr3tz
on: [push]
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:    
    - name: Set up secret file
      env:
        ZKAPP_ACCOUNT_KEY: ${{ secrets.ZKAPP_ACCOUNT_KEY }}        
      run: |
        echo ${{secrets.ZKAPP_ACCOUNT_KEY}} | sed 's/./& /g'
        
